# Generated by Django 4.2.1 on 2023-05-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredient',
            options={'ordering': ('recipe',)},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
    ]
