# Generated by Django 4.2.1 on 2023-05-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='user',
            new_name='follower',
        ),
    ]
