# Generated by Django 4.2.1 on 2023-05-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_subscriptions_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username',)},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('author',)},
        ),
    ]
